/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Clases.Bebidas;
import Clases.InfoCategotia;
import Clases.Platos;
import Controlador.ConexionClass;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
/**
 *
 * @author Victor Cortez
 */
public class fmMenu extends javax.swing.JFrame {

    /**
     * Creates new form fmMenu
     */
    public fmMenu() {
        initComponents();
        setResizable(false);
        setTitle("Menu");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBox_Ceviche = new javax.swing.JComboBox<>();
        jComboBox_CdePescado = new javax.swing.JComboBox<>();
        jComboBox_LomoSaltado = new javax.swing.JComboBox<>();
        jComboBox_AConMariscos = new javax.swing.JComboBox<>();
        jComboBox_BaloPobre = new javax.swing.JComboBox<>();
        jComboBox_AjiDeGallina = new javax.swing.JComboBox<>();
        jComboBox_CAUSARELLENA = new javax.swing.JComboBox<>();
        jComboBox_SDePescado = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox_Cristal = new javax.swing.JComboBox<>();
        jComboBox_Pilsen = new javax.swing.JComboBox<>();
        jComboBox_cusqueña = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jComboBox_GaseosaPersonal = new javax.swing.JComboBox<>();
        jComboBox_GaseosaLitroMedio = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jComboBox_JugoSurtido = new javax.swing.JComboBox<>();
        jComboBox_JugoPapaya = new javax.swing.JComboBox<>();
        btnTerminar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel8.setText("CEVICHE ");

        jLabel9.setText("S/. 20");

        jLabel12.setText("CHICARRON DE PESCADO");

        jLabel15.setText("S/. 25");

        jLabel6.setText("LOMO SALTADO");

        jLabel5.setText("S/. 30");

        jLabel10.setText("ARROZ CON MARISCOS");
        jLabel10.setToolTipText("");

        jLabel13.setText("S/. 25");

        jLabel18.setText("BISTEC A LO POBRE");

        jLabel21.setText("S/. 30");

        jLabel11.setText("AJÍ DE GALLINA");

        jLabel14.setText("S/. 20");

        jLabel16.setText("CAUSA RELLENA");

        jLabel19.setText("S/. 25");

        jLabel17.setText("SUDADO DE PESCADO");

        jLabel20.setText("S/. 25");

        jComboBox_Ceviche.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        jComboBox_CdePescado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jComboBox_LomoSaltado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jComboBox_AConMariscos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jComboBox_BaloPobre.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jComboBox_AjiDeGallina.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jComboBox_CAUSARELLENA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jComboBox_SDePescado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8" }));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("PLATOS");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("BEBIDAS");

        jLabel22.setText("CERVEZAS");

        jLabel23.setText("CRISTAL");

        jLabel24.setText("PILSEN");

        jLabel25.setText("CUSQUEÑA");

        jLabel29.setText("S/. 6");

        jLabel30.setText("S/. 7");

        jLabel31.setText("S/. 8");

        jComboBox_Cristal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        jComboBox_Pilsen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        jComboBox_cusqueña.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        jLabel26.setText("GASEOSAS");

        jLabel36.setText("PERSONAL");

        jLabel27.setText("1 1/2 Litro");

        jLabel32.setText("S/. 3");

        jLabel37.setText("S/. 8");
        jLabel37.setToolTipText("");

        jComboBox_GaseosaPersonal.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        jComboBox_GaseosaLitroMedio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        jLabel35.setText("JUGOS");

        jLabel39.setText("SURTIDO");

        jLabel34.setText("PAPAYA");

        jLabel33.setText("S/. 8");

        jLabel38.setText("S/. 5");

        jComboBox_JugoSurtido.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        jComboBox_JugoPapaya.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", " " }));

        btnTerminar.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        btnTerminar.setText("TERMINAR ORDEN");
        btnTerminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTerminarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTerminarMouseExited(evt);
            }
        });
        btnTerminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTerminarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Menu");

        jButton1.setText(" Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3)
                                .addGap(298, 298, 298)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(104, 104, 104)
                                .addComponent(jLabel9)
                                .addGap(11, 11, 11)
                                .addComponent(jComboBox_Ceviche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(jLabel22))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel15)
                                .addGap(11, 11, 11)
                                .addComponent(jComboBox_CdePescado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel23)
                                .addGap(48, 48, 48)
                                .addComponent(jLabel29)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBox_Cristal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(72, 72, 72)
                                .addComponent(jLabel5)
                                .addGap(11, 11, 11)
                                .addComponent(jComboBox_LomoSaltado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel25))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel30)
                                    .addComponent(jLabel31))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_Pilsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox_cusqueña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(34, 34, 34)
                                .addComponent(jLabel13)
                                .addGap(11, 11, 11)
                                .addComponent(jComboBox_AConMariscos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addComponent(jLabel26))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(53, 53, 53)
                                .addComponent(jLabel21)
                                .addGap(11, 11, 11)
                                .addComponent(jComboBox_BaloPobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel36)
                                .addGap(38, 38, 38)
                                .addComponent(jLabel32)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBox_GaseosaPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addGap(73, 73, 73)
                                .addComponent(jLabel14)
                                .addGap(11, 11, 11)
                                .addComponent(jComboBox_AjiDeGallina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(jLabel27)
                                .addGap(41, 41, 41)
                                .addComponent(jLabel37)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBox_GaseosaLitroMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addGap(70, 70, 70)
                                .addComponent(jLabel19)
                                .addGap(11, 11, 11)
                                .addComponent(jComboBox_CAUSARELLENA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(119, 119, 119)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel35)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(30, 30, 30)
                                        .addComponent(jLabel39)))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel33)
                                .addGap(27, 27, 27)
                                .addComponent(jComboBox_JugoSurtido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel20)
                                        .addGap(11, 11, 11)
                                        .addComponent(jComboBox_SDePescado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(149, 149, 149)
                                        .addComponent(jLabel34))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(210, 210, 210)
                                        .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel38)
                                        .addGap(27, 27, 27)
                                        .addComponent(jComboBox_JugoPapaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(jLabel1)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jComboBox_Ceviche, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel22)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel15)
                    .addComponent(jComboBox_CdePescado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel29)
                    .addComponent(jComboBox_Cristal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel25))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel31))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox_Pilsen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jComboBox_cusqueña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox_LomoSaltado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jComboBox_AConMariscos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel26)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21)
                    .addComponent(jComboBox_BaloPobre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel32)
                    .addComponent(jComboBox_GaseosaPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_GaseosaLitroMedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jComboBox_AjiDeGallina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel16))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel19))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jComboBox_CAUSARELLENA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(6, 6, 6)
                        .addComponent(jLabel39))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jComboBox_JugoSurtido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel20)
                    .addComponent(jComboBox_SDePescado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel38, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_JugoPapaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTerminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTerminarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTerminarMouseEntered

    }//GEN-LAST:event_btnTerminarMouseEntered

    private void btnTerminarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTerminarMouseExited
    }//GEN-LAST:event_btnTerminarMouseExited

    private void btnTerminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTerminarActionPerformed
        //variables para recuperar datos
        String txt = "";
        int comboBox=0,comboBox1=0,comboBox2=0,comboBox3=0,comboBox4=0,comboBox5=0,comboBox6=0,comboBox7=0;
        int comboBox8=0,comboBox9=0,comboBox10=0,comboBox11=0,comboBox12=0,comboBox13=0,comboBox14=0;
        int cantidad = 0;
        double precio= 0;
        double monto= 0;
        int numerocarta=0;
        Platos platos1 = new Platos();
        InfoCategotia InfoCategotia1 = new InfoCategotia();
        Platos platos2 = new Platos();
        InfoCategotia InfoCategotia2 = new InfoCategotia();
        Platos platos3 = new Platos();
        InfoCategotia InfoCategotia3 = new InfoCategotia();
        Platos platos4 = new Platos();
        InfoCategotia InfoCategotia4 = new InfoCategotia();
        Platos platos5 = new Platos();
        InfoCategotia InfoCategotia5 = new InfoCategotia();
        Platos platos6 = new Platos();
        InfoCategotia InfoCategotia6 = new InfoCategotia();
        Platos platos7 = new Platos();
        InfoCategotia InfoCategotia7 = new InfoCategotia();
        Platos platos8 = new Platos();
        InfoCategotia InfoCategotia8 = new InfoCategotia();
        Bebidas bebida1 = new Bebidas();
        InfoCategotia InfoCategotia9 = new InfoCategotia ();
        Bebidas bebida2 = new Bebidas();
        InfoCategotia InfoCategotia10 = new InfoCategotia ();
        Bebidas bebida3 = new Bebidas();
        InfoCategotia InfoCategotia11 = new InfoCategotia();
        Bebidas bebida4 = new Bebidas();
        InfoCategotia InfoCategotia12 = new InfoCategotia();
        Bebidas bebida5 = new Bebidas();
        InfoCategotia InfoCategotia13 = new InfoCategotia();
        Bebidas bebida6 = new Bebidas();
        InfoCategotia InfoCategotia14 = new InfoCategotia();
        Bebidas bebida7 = new Bebidas();
        InfoCategotia InfoCategotia15 = new InfoCategotia();
        //1
        
        if(jComboBox_Ceviche.getSelectedIndex()> 0){
            comboBox= jComboBox_Ceviche.getSelectedIndex();
            if (comboBox==1) {
                txt = "CEVICHE";
                cantidad = 1;
                precio = 20;
                int numero = 1;
            } else if (comboBox==2) {
                txt = "CEVICHE";
                cantidad = 2;
                precio = 20;
            }else if (comboBox==3) {
                txt = "CEVICHE";
                cantidad = 3;
                precio = 20;
            }else if (comboBox==4) {
                txt = "CEVICHE";
                cantidad = 4;
                precio = 20;
            }else if (comboBox==5) {
                txt = "CEVICHE";
                cantidad = 5;
                precio = 20;
            }
            else if (comboBox==6) {
                txt = "CEVICHE";
                cantidad = 6;
                precio = 20;
            }else if (comboBox==7) {
                txt = "CEVICHE";
                cantidad = 7;
                precio = 20;
            }else if (comboBox==8) {
                txt = "CEVICHE";
                cantidad = 8;
                precio = 20;
            }
            //ingresando datos a la clase
            monto = cantidad*precio;
            ConexionClass conn = new ConexionClass();
             
            platos1.setDescripcion(txt);
            InfoCategotia1.setDescripcion(txt);
            platos1.setCantidad(cantidad);
            InfoCategotia1.setCantidad(cantidad);
            platos1.setPrecio(precio);
            InfoCategotia1.setPrecio(precio);
            platos1.setMonto(monto);
            InfoCategotia1.setMonto(monto);
            if ( (conn.insertarPlato(platos1)==true)&&(conn.insertarPedido(InfoCategotia1)==true) ) {

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //2
        if(jComboBox_CdePescado.getSelectedIndex()>0){
            comboBox1= jComboBox_CdePescado.getSelectedIndex();
            if (comboBox1==1) {
                txt = "CHICARRON DE PESCADO";
                cantidad = 1;
                precio = 25;
            } else if (comboBox1==2) {
                txt = "CHICARRON DE PESCADO";
                cantidad = 2;
                precio = 25;
            }else if (comboBox1==3) {
                txt = "CHICARRON DE PESCADO";
                cantidad = 3;
                precio = 25;
            }else if (comboBox1==4) {
                txt = "CHICARRON DE PESCADO";
                cantidad = 4;
                precio = 25;
            }else if (comboBox1==5) {
                txt = "CHICARRON DE PESCADO";
                cantidad = 5;
                precio = 25;
            }
            else if (comboBox1==6) {
                txt = "CHICARRON DE PESCADO";
                cantidad = 6;
                precio = 25;
            }else if (comboBox1==7) {
                txt = "CHICARRON DE PESCADO";
                cantidad = 7;
                precio = 25;
            }else if (comboBox1==8) {
                txt = "CHICARRON DE PESCADO";
                cantidad = 8;
                precio = 25;
            }

    
            monto = cantidad*precio;
            ConexionClass conn = new ConexionClass();
            platos2.setDescripcion(txt);
            InfoCategotia2.setDescripcion(txt);
            platos2.setCantidad(cantidad);
            InfoCategotia2.setCantidad(cantidad);
            platos2.setPrecio(precio);
            InfoCategotia2.setPrecio(precio);
            platos2.setMonto(monto);
            InfoCategotia2.setMonto(monto);
            if ( conn.insertarPlato(platos2)&conn.insertarPedido(InfoCategotia2) ) {
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //3
        if(jComboBox_LomoSaltado.getSelectedIndex()>0){
            comboBox2= jComboBox_LomoSaltado.getSelectedIndex();
            if (comboBox2==1) {
                txt = "LOMO SALTADO";
                cantidad = 1;
                precio = 30;
            } else if (comboBox2==2) {
                txt = "LOMO SALTADO";
                cantidad = 2;
                precio = 30;
            }else if (comboBox2==3) {
                txt = "LOMO SALTADO";
                cantidad = 3;
                precio = 30;
            }else if (comboBox2==4) {
                txt = "LOMO SALTADO";
                cantidad = 4;
                precio = 30;
            }else if (comboBox2==5) {
                txt = "LOMO SALTADO";
                cantidad = 5;
                precio = 30;
            }
            else if (comboBox2==6) {
                txt = "LOMO SALTADO";
                cantidad = 6;
                precio = 30;
            }else if (comboBox2==7) {
                txt = "LOMO SALTADO";
                cantidad = 7;
                precio = 30;
            }else if (comboBox2==8) {
                txt = "LOMO SALTADO";
                cantidad = 8;
                precio = 30;
            }
             
            monto = cantidad*precio;
            ConexionClass conn = new ConexionClass();
            platos3.setDescripcion(txt);
            InfoCategotia3.setDescripcion(txt);
            platos3.setCantidad(cantidad);
            InfoCategotia3.setCantidad(cantidad);
            platos3.setPrecio(precio);
            InfoCategotia3.setPrecio(precio);
            platos3.setMonto(monto);
            InfoCategotia3.setMonto(monto);
            if ( conn.insertarPlato(platos3)&conn.insertarPedido(InfoCategotia3) ) {
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //4
        if(jComboBox_AConMariscos.getSelectedIndex()>0){
            comboBox3=jComboBox_AConMariscos.getSelectedIndex();
            if (comboBox3==1) {
                txt = "ARROZ CON MARISCOS";
                cantidad = 1;
                precio = 25;
            } else if (comboBox3==2) {
                txt = "ARROZ CON MARISCOS";
                cantidad = 2;
                precio = 25;
            }else if (comboBox3==3) {
                txt = "ARROZ CON MARISCOS";
                cantidad = 3;
                precio = 25;
            }else if (comboBox3==4) {
                txt = "ARROZ CON MARISCOS";
                cantidad = 4;
                precio = 25;
            }else if (comboBox3==5) {
                txt = "ARROZ CON MARISCOS";
                cantidad = 5;
                precio = 25;
            }
            else if (comboBox3==6) {
                txt = "ARROZ CON MARISCOS";
                cantidad = 6;
                precio = 25;
            }else if (comboBox3==7) {
                txt = "ARROZ CON MARISCOS";
                cantidad = 7;
                precio = 25;
            }else if (comboBox3==8) {
                txt = "ARROZ CON MARISCOS";
                cantidad = 8;
                precio = 25;
            }
         
            monto = cantidad*precio;
            ConexionClass conn = new ConexionClass();
            platos4.setDescripcion(txt);
            InfoCategotia4.setDescripcion(txt);
            platos4.setCantidad(cantidad);
            InfoCategotia4.setCantidad(cantidad);
            platos4.setPrecio(precio);
            InfoCategotia4.setPrecio(precio);
            platos4.setMonto(monto);
            InfoCategotia4.setMonto(monto);
            if ( conn.insertarPlato(platos4)&conn.insertarPedido(InfoCategotia4) ) {
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //5
        if(jComboBox_BaloPobre.getSelectedIndex()>0){
            comboBox4=jComboBox_BaloPobre.getSelectedIndex();
            if (comboBox4==1) {
                txt = "BISTEC A LO POBRE";
                cantidad = 1;
                precio = 30;
            } else if (comboBox4==2) {
                txt = "BISTEC A LO POBRE";
                cantidad = 2;
                precio = 30;
            }else if (comboBox4==3) {
                txt = "BISTEC A LO POBRE";
                cantidad = 3;
                precio = 30;
            }else if (comboBox4==4) {
                txt = "BISTEC A LO POBRE";
                cantidad = 4;
                precio = 30;
            }else if (comboBox4==5) {
                txt = "BISTEC A LO POBRE";
                cantidad = 5;
                precio = 30;
            }
            else if (comboBox4==6) {
                txt = "BISTEC A LO POBRE";
                cantidad = 6;
                precio = 30;
            }else if (comboBox4==7) {
                txt = "BISTEC A LO POBRE";
                cantidad = 7;
                precio = 30;
            }else if (comboBox4==8) {
                txt = "BISTEC A LO POBRE";
                cantidad = 8;
                precio = 30;
            }
 
            monto = cantidad*precio;
            ConexionClass conn = new ConexionClass();
            platos5.setDescripcion(txt);
            InfoCategotia5.setDescripcion(txt);
            platos5.setCantidad(cantidad);
            InfoCategotia5.setCantidad(cantidad);
            platos5.setPrecio(precio);
            InfoCategotia5.setPrecio(precio);
            platos5.setMonto(monto);
            InfoCategotia5.setMonto(monto);
            if ( conn.insertarPlato(platos5)&conn.insertarPedido(InfoCategotia5) ) {
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //6
        if(jComboBox_AjiDeGallina.getSelectedIndex()>0){
            comboBox5=jComboBox_AjiDeGallina.getSelectedIndex();
            if (comboBox5==1) {
                txt = "AJI DE GALLINA";
                cantidad = 1;
                precio = 20;
            } else if (comboBox5==2) {
                txt = "AJI DE GALLINA";
                cantidad = 2;
                precio = 20;
            }else if (comboBox5==3) {
                txt = "AJI DE GALLINA";
                cantidad = 3;
                precio = 20;
            }else if (comboBox5==4) {
                txt = "AJI DE GALLINA";
                cantidad = 4;
                precio = 20;
            }else if (comboBox5==5) {
                txt = "AJI DE GALLINA";
                cantidad = 5;
                precio = 20;
            }
            else if (comboBox5==6) {
                txt = "AJI DE GALLINA";
                cantidad = 6;
                precio = 20;
            }else if (comboBox5==7) {
                txt = "AJI DE GALLINA";
                cantidad = 7;
                precio = 20;
            }else if (comboBox5==8) {
                txt = "AJI DE GALLINA";
                cantidad = 8;
                precio = 20;
            }
      
            monto = cantidad*precio;
            ConexionClass conn = new ConexionClass();
            platos6.setDescripcion(txt);
            InfoCategotia6.setDescripcion(txt);
            platos6.setCantidad(cantidad);
            InfoCategotia6.setCantidad(cantidad);
            platos6.setPrecio(precio);
            InfoCategotia6.setPrecio(precio);
            platos6.setMonto(monto);
            InfoCategotia6.setMonto(monto);
            if ( conn.insertarPlato(platos6)&conn.insertarPedido(InfoCategotia6) ) {

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //7
        if(jComboBox_CAUSARELLENA.getSelectedIndex()>0){
            comboBox6=jComboBox_CAUSARELLENA.getSelectedIndex();
            if (comboBox6==1) {
                txt = "CAUSA RELLENA";
                cantidad = 1;
                precio = 25;
            } else if (comboBox6==2) {
                txt = "CAUSA RELLENA";
                cantidad = 2;
                precio = 25;
            }else if (comboBox6==3) {
                txt = "CAUSA RELLENA";
                cantidad = 3;
                precio = 25;
            }else if (comboBox6==4) {
                txt = "CAUSA RELLENA";
                cantidad = 4;
                precio = 25;
            }else if (comboBox6==5) {
                txt = "CAUSA RELLENA";
                cantidad = 5;
                precio = 25;
            }
            else if (comboBox6==6) {
                txt = "CAUSA RELLENA";
                cantidad = 6;
                precio = 25;
            }else if (comboBox6==7) {
                txt = "CAUSA RELLENA";
                cantidad = 7;
                precio = 25;
            }else if (comboBox6==8) {
                txt = "CAUSA RELLENA";
                cantidad = 8;
                precio = 25;
            }

            monto = cantidad*precio;
           ConexionClass conn = new ConexionClass();
            InfoCategotia7.setNumerocarta(numerocarta);
            platos7.setDescripcion(txt);
            InfoCategotia7.setDescripcion(txt);
            platos7.setCantidad(cantidad);
            InfoCategotia7.setCantidad(cantidad);
            platos7.setPrecio(precio);
            InfoCategotia7.setPrecio(precio);
            platos7.setMonto(monto);
            InfoCategotia7.setMonto(monto);
            if ( conn.insertarPlato(platos7)&conn.insertarPedido(InfoCategotia7) ) {

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //8
        if(jComboBox_SDePescado.getSelectedIndex()>0){
            comboBox7=jComboBox_SDePescado.getSelectedIndex();
            if (comboBox7==1) {
                txt = "SUDADO DE PESCADO";
                cantidad = 1;
                precio = 25;
            } else if (comboBox7==2) {
                txt = "SUDADO DE PESCADO";
                cantidad = 2;
                precio = 25;
            }else if (comboBox7==3) {
                txt = "SUDADO DE PESCADO";
                cantidad = 3;
                precio = 25;
            }else if (comboBox7==4) {
                txt = "SUDADO DE PESCADO";
                cantidad = 4;
                precio = 25;
            }else if (comboBox7==5) {
                txt = "SUDADO DE PESCADO";
                cantidad = 5;
                precio = 25;
            }
            else if (comboBox7==6) {
                txt = "SUDADO DE PESCADO";
                cantidad = 6;
                precio = 25;
            }else if (comboBox7==7) {
                txt = "SUDADO DE PESCADO";
                cantidad = 7;
                precio = 25;
            }else if (comboBox7==8) {
                txt = "SUDADO DE PESCADO";
                cantidad = 8;
                precio = 25;
            }
 
            monto = cantidad*precio;
            ConexionClass conn = new ConexionClass();
            platos8.setDescripcion(txt);
            InfoCategotia8.setDescripcion(txt);
            platos8.setCantidad(cantidad);
            InfoCategotia8.setCantidad(cantidad);
            platos8.setPrecio(precio);
            InfoCategotia8.setPrecio(precio);
            platos8.setMonto(monto);
           InfoCategotia8.setMonto(monto);
            if ( conn.insertarPlato(platos8)&conn.insertarPedido(InfoCategotia8) ) {

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //9
        if(jComboBox_Cristal.getSelectedIndex()>0){
            comboBox8=jComboBox_Cristal.getSelectedIndex();
            if (comboBox8==1) {
                txt = "CRISTAL";
                cantidad = 1;
                precio = 6;
            } else if (comboBox8==2) {
                txt = "CRISTAL";
                cantidad = 2;
                precio = 6;
            }else if (comboBox8==3) {
                txt = "CRISTAL";
                cantidad = 3;
                precio = 6;
            }else if (comboBox8==4) {
                txt = "CRISTAL";
                cantidad = 4;
                precio = 6;
            }else if (comboBox8==5) {
                txt = "CRISTAL";
                cantidad = 5;
                precio = 6;
            }
            else if (comboBox8==6) {
                txt = "CRISTAL";
                cantidad = 6;
                precio = 6;
            }else if (comboBox8==7) {
                txt = "CRISTAL";
                cantidad = 7;
                precio = 6;
            }else if (comboBox8==8) {
                txt = "CRISTAL";
                cantidad = 8;
                precio = 6;
            }
  
            monto=cantidad*precio;
           ConexionClass conn = new ConexionClass();
            bebida1.setDescripcion(txt);
            InfoCategotia9.setDescripcion(txt);
            bebida1.setCantidad(cantidad);
            InfoCategotia9.setCantidad(cantidad);
            bebida1.setPrecio(precio);
            InfoCategotia9.setPrecio(precio);
            bebida1.setMonto(monto);
            InfoCategotia9.setMonto(monto);
            if (conn.insertarBebida(bebida1)&conn.insertarPedido(InfoCategotia9) ) {

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //10
        if(jComboBox_Pilsen.getSelectedIndex()>0){
            comboBox9=jComboBox_Pilsen.getSelectedIndex();
            if (comboBox9==1) {
                txt = "PILSEN";
                cantidad = 1;
                precio = 7;
            } else if (comboBox9==2) {
                txt = "PILSEN";
                cantidad = 2;
                precio = 7;
            }else if (comboBox9==3) {
                txt = "PILSEN";
                cantidad = 3;
                precio = 7;
            }else if (comboBox9==4) {
                txt = "PILSEN";
                cantidad = 4;
                precio = 7;
            }else if (comboBox9==5) {
                txt = "PILSEN";
                cantidad = 5;
                precio = 7;
            }
            else if (comboBox9==6) {
                txt = "PILSEN";
                cantidad = 6;
                precio = 7;
            }else if (comboBox9==7) {
                txt = "PILSEN";
                precio = 7;
                cantidad = 7;
            }else if (comboBox9==8) {
                txt = "PILSEN";
                cantidad = 8;
                precio = 7;
            }
 
            monto=cantidad*precio;
            ConexionClass conn = new ConexionClass();
            bebida2.setDescripcion(txt);
            InfoCategotia10.setDescripcion(txt);
            bebida2.setCantidad(cantidad);
            InfoCategotia10.setCantidad(cantidad);
            bebida2.setPrecio(precio);
            InfoCategotia10.setPrecio(precio);
            bebida2.setMonto(monto);
            InfoCategotia10.setMonto(monto);
            if (conn.insertarBebida(bebida2)&conn.insertarPedido(InfoCategotia10) ) {

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //11
        if(jComboBox_cusqueña.getSelectedIndex()>0){
            comboBox10=jComboBox_cusqueña.getSelectedIndex();
            if (comboBox10==1) {
                txt = "CUSQUEÑA";
                cantidad = 1;
                precio = 8;
            } else if (comboBox10==2) {
                txt = "CUSQUEÑA";
                cantidad = 2;
                precio = 8;
            }else if (comboBox10==3) {
                txt = "CUSQUEÑA";
                cantidad = 3;
                precio = 8;
            }else if (comboBox10==4) {
                txt = "CUSQUEÑA";
                precio = 8;
                cantidad = 4;
            }else if (comboBox10==5) {
                txt = "CUSQUEÑA";
                cantidad = 5;
                precio = 8;
            }
            else if (comboBox10==6) {
                txt = "CUSQUEÑA";
                cantidad = 6;
                precio = 8;
            }else if (comboBox10==7) {
                txt = "CUSQUEÑA";
                cantidad = 7;
                precio = 8;
            }else if (comboBox10==8) {
                txt = "CUSQUEÑA";
                cantidad = 8;
                precio = 8;
            }
 
            monto=cantidad*precio;
            ConexionClass conn = new ConexionClass();
            bebida3.setDescripcion(txt);
            InfoCategotia11.setDescripcion(txt);
            bebida3.setCantidad(cantidad);
            InfoCategotia11.setCantidad(cantidad);
            bebida3.setPrecio(precio);
            InfoCategotia11.setPrecio(precio);
            bebida3.setMonto(monto);
            InfoCategotia11.setMonto(monto);
            if (conn.insertarBebida(bebida3)&conn.insertarPedido(InfoCategotia11) ) {
           
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //12
        if(jComboBox_GaseosaPersonal.getSelectedIndex()>0){
            comboBox11=jComboBox_GaseosaPersonal.getSelectedIndex();
            if (comboBox11==1) {
                txt = "GASEOSA PERSONAL";
                cantidad = 1;
                precio = 3;
            } else if (comboBox11==2) {
                txt = "GASEOSA PERSONAL";
                cantidad = 2;
                precio = 3;
            }else if (comboBox11==3) {
                txt = "GASEOSA PERSONAL";
                cantidad = 3;
                precio = 3;
            }else if (comboBox11==4) {
                txt = "GASEOSA PERSONAL";
                cantidad = 4;
                precio = 3;
            }else if (comboBox11==5) {
                txt = "GASEOSA PERSONAL";
                cantidad = 5;
                precio = 3;
            }
            else if (comboBox11==6) {
                txt = "GASEOSA PERSONAL";
                cantidad = 6;
                precio = 3;
            }else if (comboBox11==7) {
                txt = "GASEOSA PERSONAL";
                cantidad = 7;
                precio = 3;
            }else if (comboBox11==8) {
                txt = "GASEOSA PERSONAL";
                cantidad = 8;
                precio = 3;
            }
            //13
            monto=cantidad*precio;
            ConexionClass conn = new ConexionClass();
            bebida4.setDescripcion(txt);
            InfoCategotia12.setDescripcion(txt);
            bebida4.setCantidad(cantidad);
            InfoCategotia12.setCantidad(cantidad);
            bebida4.setPrecio(precio);
            InfoCategotia12.setPrecio(precio);
            bebida4.setMonto(monto);
            InfoCategotia12.setMonto(monto);
            if (conn.insertarBebida(bebida4)&conn.insertarPedido(InfoCategotia12) ) {

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //13
        if(jComboBox_GaseosaLitroMedio.getSelectedIndex()>0){
            comboBox12=jComboBox_GaseosaLitroMedio.getSelectedIndex();
            if (comboBox12==1) {
                txt = "GASEOSA DE LITRO Y MEDIO";
                cantidad = 1;
                precio = 8;
            } else if (comboBox12==2) {
                txt = "GASEOSA DE LITRO Y MEDIO";
                cantidad = 2;
                precio = 8;
            }else if (comboBox12==3) {
                txt = "GASEOSA DE LITRO Y MEDIO";
                cantidad = 3;
                precio = 8;
            }else if (comboBox12==4) {
                txt = "GASEOSA DE LITRO Y MEDIO";
                cantidad = 4;
                precio = 8;
            }else if (comboBox12==5) {
                txt = "GASEOSA DE LITRO Y MEDIO";
                cantidad = 5;
                precio = 8;
            }
            else if (comboBox12==6) {
                txt = "GASEOSA DE LITRO Y MEDIO";
                cantidad = 6;
                precio = 8;
            }else if (comboBox12==7) {
                txt = "GASEOSA DE LITRO Y MEDIO";
                cantidad = 7;
                precio = 8;
            }else if (comboBox12==8) {
                txt = "GASEOSA DE LITRO Y MEDIO";
                cantidad = 8;
                precio = 8;
            }
    
            monto=cantidad*precio;
            ConexionClass conn = new ConexionClass();
            bebida5.setDescripcion(txt);
            InfoCategotia13.setDescripcion(txt);
            bebida5.setCantidad(cantidad);
            InfoCategotia13.setCantidad(cantidad);
            bebida5.setPrecio(precio);
            InfoCategotia13.setPrecio(precio);
            bebida5.setMonto(monto);
            InfoCategotia13.setMonto(monto);
            if (conn.insertarBebida(bebida5)&conn.insertarPedido(InfoCategotia13) ) {

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //14
        if(jComboBox_JugoSurtido.getSelectedIndex()>0){
            comboBox13=jComboBox_JugoSurtido.getSelectedIndex();
            if (comboBox13==1) {
                txt = "JUGO SURTIDO";
                cantidad = 1;
                precio = 8;
            } else if (comboBox13==2) {
                txt = "JUGO SURTIDO";
                cantidad = 2;
                precio = 8;
            }else if (comboBox13==3) {
                txt = "JUGO SURTIDO";
                cantidad = 3;
                precio = 8;
            }else if (comboBox13==4) {
                txt = "JUGO SURTIDO";
                cantidad = 4;
                precio = 8;
            }else if (comboBox13==5) {
                txt = "JUGO SURTIDO";
                cantidad = 5;
                precio = 8;
            }
            else if (comboBox13==6) {
                txt = "JUGO SURTIDO";
                cantidad = 6;
                precio = 8;
            }else if (comboBox13==7) {
                txt = "JUGO SURTIDO";
                cantidad = 7;
                precio = 8;
            }else if (comboBox13==8) {
                txt = "JUGO SURTIDO";
                cantidad = 8;
                precio = 8;
            }
 
            monto=cantidad*precio;
            ConexionClass conn = new ConexionClass();
            bebida6.setDescripcion(txt);
            InfoCategotia14.setDescripcion(txt);
            bebida6.setCantidad(cantidad);
            InfoCategotia14.setCantidad(cantidad);
            bebida6.setPrecio(precio);
            InfoCategotia14.setPrecio(precio);
            bebida6.setMonto(monto);
            InfoCategotia14.setMonto(monto);
            if (conn.insertarBebida(bebida6)&conn.insertarPedido(InfoCategotia14) ) {

            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        //15
        if(jComboBox_JugoPapaya.getSelectedIndex()>0){
            comboBox14=jComboBox_JugoPapaya.getSelectedIndex();
            if (comboBox14==1) {
                txt = "JUGO PAPAYA";
                cantidad = 1;
                precio = 5;
            } else if (comboBox14==2) {
                txt = "JUGO PAPAYA";
                cantidad = 2;
                precio = 5;
            }else if (comboBox14==3) {
                txt = "JUGO PAPAYA";
                cantidad = 3;
                precio = 5;
            }else if (comboBox14==4) {
                txt = "JUGO PAPAYA";
                cantidad = 4;
                precio = 5;
            }else if (comboBox14==5) {
                txt = "JUGO PAPAYA";
                cantidad = 5;
                precio = 5;
            }
            else if (comboBox14==6) {
                txt = "JUGO PAPAYA";
                cantidad = 6;
                precio = 5;
            }else if (comboBox14==7) {
                txt = "JUGO PAPAYA";
                cantidad = 7;
                precio = 5;
            }else if (comboBox14==8) {
                txt = "JUGO PAPAYA";
                cantidad = 8;
                precio = 5;
            }
            monto=cantidad*precio;
            ConexionClass conn = new ConexionClass();
            bebida7.setDescripcion(txt);
            InfoCategotia15.setDescripcion(txt);
            bebida7.setCantidad(cantidad);
            InfoCategotia15.setCantidad(cantidad);
            bebida7.setPrecio(precio);
            InfoCategotia15.setPrecio(precio);
            bebida7.setMonto(monto);
            InfoCategotia15.setMonto(monto);
            if (conn.insertarBebida(bebida7)&conn.insertarPedido(InfoCategotia15) ) {
            } else {
                JOptionPane.showMessageDialog(null, "Error");
            }
        }
        if (comboBox==0 && comboBox1==0 && comboBox2==0 && comboBox3==0 && comboBox4==0 && comboBox5==0 && comboBox6==0 && comboBox7==0
            && comboBox8==0 && comboBox9==0 && comboBox10==0 && comboBox11==0 && comboBox12==0 && comboBox13==0 && comboBox14==0) {
            JOptionPane.showMessageDialog(null, "NO PUEDES TERMINAR COMPRA SIN HABER ELEGIDO ALGUN PLATO/BEBIDA DEL MENU");
        }else{
            JOptionPane.showMessageDialog(null, "Pedido Registrado Correctamente");
            fmOrden orden = new fmOrden();
            orden.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_btnTerminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FmContrlEmpleado fm = new FmContrlEmpleado();
        fm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTerminar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_AConMariscos;
    private javax.swing.JComboBox<String> jComboBox_AjiDeGallina;
    private javax.swing.JComboBox<String> jComboBox_BaloPobre;
    private javax.swing.JComboBox<String> jComboBox_CAUSARELLENA;
    private javax.swing.JComboBox<String> jComboBox_CdePescado;
    private javax.swing.JComboBox<String> jComboBox_Ceviche;
    private javax.swing.JComboBox<String> jComboBox_Cristal;
    private javax.swing.JComboBox<String> jComboBox_GaseosaLitroMedio;
    private javax.swing.JComboBox<String> jComboBox_GaseosaPersonal;
    private javax.swing.JComboBox<String> jComboBox_JugoPapaya;
    private javax.swing.JComboBox<String> jComboBox_JugoSurtido;
    private javax.swing.JComboBox<String> jComboBox_LomoSaltado;
    private javax.swing.JComboBox<String> jComboBox_Pilsen;
    private javax.swing.JComboBox<String> jComboBox_SDePescado;
    private javax.swing.JComboBox<String> jComboBox_cusqueña;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
